### ISSUE TITLE
No Flow from bytecode to native 

### ISSUE THREAD

**Issue by 2315433606** [JordanSamhi/JuCify#13]
Hello, When I use JuCify to run the benchmark app proxy_double.apk, using following command:
-a /home/zjl/Project/JuCify/benchApps/proxy_double.apk
-p /home/zjl/Project/platform
-f /home/zjl/Project/output/proxy_double_result/libnative-lib.so.dot:/home/zjl/Project/output/proxy_double_result/libnative-lib.so.result
-b /home/zjl/Project/graph/before.txt
-c /home/zjl/Project/graph/result.txt
-e /home/zjl/Project/graph/proxy_double.dot
-ta
it shows results:
JuCify v0.1 started on Wed Nov 29 16:33:27 CST 2023

[*] Processing: lu.uni.trux.proxy_double
[*] Loading binary call-graphs + java-to-native and native-to-java links...
[*] Adding java-to-native Edge from <lu.uni.trux.proxy_double.MainActivity: void onCreate(android.os.Bundle)> to <DummyBinaryClass: java.lang.String Java_lu_uni_trux_proxy_1double_MainActivity_nativeProxy(java.lang.String)>
    public java.lang.String Java_lu_uni_trux_proxy_1double_MainActivity_nativeProxy(java.lang.String)
    {
        DummyBinaryClass $r0, $r2;
        java.lang.String $r1;

        $r0 := @this: DummyBinaryClass;

        $r1 := @parameter0: java.lang.String;

        $r2 = $r0;

        return $r2;

        nop;
    }

[✓] Binary callgraph imported.
[*] Exporting call graph to /home/zjl/Project/graph/proxy_double.dot...
[✓] Callgraph exported.
Results:
 - App name: proxy_double
 - Analysis elapsed time: 2
 - Instrumentation elapsed time: 0
 - Taint Analysis elapsed time: 0
 - Number of nodes before Jucify: 16
 - Number of nodes after Jucify: 111
 - Number of edges before Jucify: 16
 - Number of edges after Jucify: 151
 - Number new Java-to-Native Call-Graph edges: 1
 - Number new Native-to-Java Call-Graph edges: 0
 - Number new Call-Graph reachable nodes: 57
 - Number new Call-Graph reachable nodes Java: 0
 - Number new Call-Graph reachable nodes Native: 57
 - Number new Call-Graph edges: 135
 - Has flow through native: No
there is no flow from bytecode to native, Did I do something wrong？Can you help me?

**Comment by JordanSamhi** [comment]
Hi,
It seems you have used JuCify manually, what if you use the main script?

**Comment by 2315433606** [comment]
I was using the script seems to be unable to package the project, import dependency that step always error, I manually import the required package, input the script command in the console. Do I have to use the main scripting ？

**Comment by JordanSamhi** [comment]
Packaging the project is one problem but once it is done you have to use the main.sh script in the scripts folder to ensure that all options are passed correctly.
Because, in your case it seems the model is not computed correctly and that is why it does not find the leak.

**Comment by 2315433606** [comment]
I use this command in the terminal, but I always get these errors. Can you help me check where the reason is? Thank you very much!
![截图 2023-11-30 14-18-10](https://github.com/JordanSamhi/JuCify/assets/150419611/0a9276e3-4385-46c2-95ce-f537c4aa4713)

**Comment by JordanSamhi** [comment]
Did you checkout to 6897c58350773987da0a2c52a99fd4ebf1edc39e ?

**Comment by 2315433606** [comment]
yes, I did.
![Uploading 截图 2023-11-30 14-39-59.png…]()

**Comment by 2315433606** [comment]
yes, I did.
![截图 2023-11-30 14-47-10](https://github.com/JordanSamhi/JuCify/assets/150419611/e7cabf25-5fcc-4e09-93ad-f3935751c5d5)
