### ISSUE TITLE
Unresolved reference 'mylib' 

### ISSUE THREAD

**Issue by beyondgjc** [JordanSamhi/JuCify#2]
from mylib.androzoo import download
from mylib.common import zipdir
What library is 'mylib'?  Please

**Comment by JordanSamhi** [comment]
Hi @beyondgjc,

This is from NativeDiscloser module (https://github.com/gaojun0816/nativediscloser).
I am not sure you need this, but still, I cc @gaojun0816, so that he can say more about this.

**Comment by gaojun0816** [comment]
Hi @beyondgjc,

mylib is a module I wrote to perform some utilization functionalities.
This module includes many personalized functions so I haven't made it public.
Do you mind letting me know which function(s) you were trying to use?
Maybe you don't need the module.
