### ISSUE TITLE
Precision on NativeFlowBench & docker image

### ISSUE THREAD

**Issue by am009** [JordanSamhi/JuCify#3]
I'm also doing research on android native code. I'm currently evaluating existing tools. I tried JuCify on [NativeFlowBench](https://github.com/arguslab/NativeFlowBench).

To make the evaluation process easily reproducible, I packed JuCify into a docker image: https://github.com/am009/JuCify/tree/6897c58_docker and https://hub.docker.com/r/warrenwjk/jucify.

After solving some problems, I finally got it running on NativeFlowBench. I modified some scripts to save the output of running jar and nativediscloser. Here is the result: [Jucify-NativeFlowBench-6897c58-2022-6-6.zip](https://github.com/JordanSamhi/JuCify/files/8841465/Jucify-NativeFlowBench-6897c58-2022-6-6.zip). Only 2 cases (native_set_field_from_arg and native_source) can be detected that have flow through native?

Besides, I have a bunch of other questions.
1.  The symbolic_expression_usage branch is currently not merged into master, so I guess this functionality is still not useable? ( The symbolic_expression_usage branch in nativediscloser is merged though). In current master branch, this seems to result in a mismatch between JuCify and nativediscloser on `.result` file format.

2. in commit 6897c58(recommended in readme), the scripts folder appears to contain a copy of nativediscloser code. and `launch_native_disclosurer.sh` is executing `python3 ./main.py` instead of `python3 ../nativediscloser/main.py` ?

3. When I run cases from NativeFlowBench, there are plenty of small problems, like 
    - `AttributeError: 'NoneType' object has no attribute 'rebased_addr'` this is fixed in https://github.com/gaojun0816/nativediscloser/commit/d0dad4438f29b6cf1eefa2eb6226e426d7a78c31#diff-beb8b2c78df610b0316d0fcbd066c83a8e2e420898f3290ec87c4ea9738e867f but not after checkout to old commit (Jucify @ 6897c58 points to nativediscloser @ 1682a22).
    - `TypeError: relocate() takes 1 positional argument but 2 were given` This exception is thrown from angr's project.py, It seems to be angr's fault?
    - `No call graph present in Scene` when analysing native_pure_direct_customized.apk. it seems to relate to https://github.com/secure-software-engineering/FlowDroid/issues/171 .

Finally, I noticed that, because of latest angr's API change, it seems not an easy task to port nativediscloser to latest Angr?

**Comment by JordanSamhi** [comment]
Hi @am009,

Thank you for reaching out.

First, regarding NativeFlowBench, it is highly dependent on the lists of sources and sinks that you consider for the taint analysis. Second, JuCify, as described in the paper, is not intended to handle purely native leaks yet. Indeed, in its current form, it reconstructs Android API calls in the native code but does not consider purely native functions, we are currently working on a more robust version.

1. It is indeed not yet usable, we are working on it.
2. At first, we used a working copy of NativeDiscloser which was still under dev. The latest version is stable. If you use the scripts provided, you will have the same environment used for the paper.

**Comment by am009** [comment]
Thanks for the response! I think I'll just use this version (6897c58) for possible future evaluation.

Regarding NativeFlowBench, can I make easy changes to improve results on it? (like adding some sources and sinks). If not or you guys don't know much about it, I guess I'll just stay with current result.

**Comment by JordanSamhi** [comment]
Actually, in order for JuCify to detect a leak, an app would need to call an Android API source whether in bytecode or in native code, same for sinks. If data is leaked in pure native code, e.g., with socket-based calls, it would not work with the current version. 
If you want to improve the result, you would have to inject Android API calls in the native call, such as:

```
jclass telephonyManagerClass = (*env).FindClass("android/telephony/TelephonyManager");
jmethodID getImeiMid = (*env).GetMethodID(telephonyManagerClass, "getDeviceId", "()Ljava/lang/String;");
jstring imei =  (jstring)(*env).CallObjectMethod(telephonyManagerObject, getImeiMid);
```

**Comment by am009** [comment]
I understand now. If JuCify cannot detect `__android_log_print` as a sink, then it's reasonable that it cannot detect cases like native_leak, native_method_overloading, native_multiple_interactions and native_multiple_libraries. (After reading through NativeFlowBench's source code).

But it's still not clear why native_heap_modify, native_set_field_from_native and native_set_field_from_arg_field cannot be detected. The sinks in these cases are in java side using `Log.i` or `Log.d`. 

`Log.i` and `Log.d` are included in src\main\resources\SourcesSinks.txt, and the sources are `TelephonyManager.getDeviceId`.

- native_heap_modify: Java side passes a `Data` instance as an argument, and Native side calls `getDeviceId` and set `data.str = imei`.
- native_set_field_from_arg_field: Native side propergates data between two `ComplexData` instances' fields.
- native_set_field_from_native: Native side set `complexData.data = getSystemService(Context.TELEPHONY_SERVICE)).getDeviceId()`.

Probably JuCify currently does not fully support field access operations? There is only GetObjcetField, no SetObjectField in [procedures.py @ 1682a2](https://github.com/gaojun0816/nativediscloser/blob/1682a223ca7b354ac82ecee71900929e829e2c8a/jni_interfaces/jni_native/procedures.py). In lateset [procedures.py](https://github.com/gaojun0816/nativediscloser/blob/7260c0167e56d7311085657baab3b5b0ee893221/jni_interfaces/jni_native/procedures.py#L139), the SetField class only does some prints.

**Comment by am009** [comment]
Thank you so much for the response.
